FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_BASE_PATH=/
ENV VITE_BASE_PATH=$VITE_BASE_PATH

RUN npm run build

FROM alpine:3.21

COPY --from=builder /app/dist /dist

CMD ["sh", "-c", "cp -r /dist/. /static/"]
