services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env # Вынести в переменную окружения типа ENV_FILE, для разделения dev/stage/prod
    environment:
      - VITE_API_TARGET="http://backend:${BACKEND_INTERNAL_PORT}" # Если не указано (dev), используется default в коде (localhost:8080)
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT}/api
      - VITE_BASE_PATH=/
      - ADMIN_LOGIN=${FRONTEND_ADMIN_LOGIN}
      - ADMIN_PASSWORD=${FRONTEND_ADMIN_PASSWORD}
    depends_on:
      back:
        condition: service_healthy
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
#    ports:
#      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DB}?sslmode=disable
      - PORT=${BACKEND_INTERNAL_PORT}
      - ADMIN_LOGIN=${BACKEND_ADMIN_LOGIN}
      - ADMIN_PASSWORD=${BACKEND_ADMIN_PASSWORD}
      - YANDEX_API_BASE=${YANDEX_API_BASE}
      - YANDEX_DISK_TOKEN=${YANDEX_DISK_TOKEN}
      - YANDEX_TABLE_PATH=${YANDEX_TABLE_PATH}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_INTERNAL_PORT}/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  db:
    image: postgres:17-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_INTERNAL_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres_data:
